"""update schema

Revision ID: 501466aa9a91
Revises: 
Create Date: 2026-03-18 01:49:21.133779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501466aa9a91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LU_authority',
    sa.Column('authority_id', sa.Integer(), nullable=False),
    sa.Column('authority_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('authority_id'),
    sa.UniqueConstraint('authority_name')
    )
    op.create_table('LU_conservation_list',
    sa.Column('conservation_list_id', sa.Integer(), nullable=False),
    sa.Column('conservation_list_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('conservation_list_id'),
    sa.UniqueConstraint('conservation_list_name')
    )
    op.create_table('LU_data_source',
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('data_source_name', sa.String(length=100), nullable=False),
    sa.Column('data_source_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('data_source_id')
    )
    op.create_table('LU_report_status',
    sa.Column('report_status_id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('report_status_id'),
    sa.UniqueConstraint('status_name')
    )
    op.create_table('LU_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('LU_taxonomy_rank',
    sa.Column('taxonomy_rank_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_rank_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('taxonomy_rank_id'),
    sa.UniqueConstraint('taxonomy_rank_name')
    )
    op.create_table('LU_conservation_status',
    sa.Column('conservation_status_id', sa.Integer(), nullable=False),
    sa.Column('conservation_status', sa.String(length=50), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('conservation_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conservation_list_id'], ['LU_conservation_list.conservation_list_id'], ),
    sa.PrimaryKeyConstraint('conservation_status_id')
    )
    op.create_table('taxonomy',
    sa.Column('taxonomy_id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=100), nullable=False),
    sa.Column('vernacular_name', sa.String(length=100), nullable=True),
    sa.Column('gbif_taxonomy_id', sa.String(length=100), nullable=True),
    sa.Column('gbif_taxonomy_url', sa.String(length=200), nullable=True),
    sa.Column('authority_id', sa.Integer(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('taxonomy_rank_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['LU_authority.authority_id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['LU_data_source.data_source_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy.taxonomy_id'], ),
    sa.ForeignKeyConstraint(['taxonomy_rank_id'], ['LU_taxonomy_rank.taxonomy_rank_id'], ),
    sa.PrimaryKeyConstraint('taxonomy_id')
    )
    with op.batch_alter_table('taxonomy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxonomy_gbif_taxonomy_id'), ['gbif_taxonomy_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_taxonomy_is_protected'), ['is_protected'], unique=False)

    op.create_table('trust_codes',
    sa.Column('trust_code_id', sa.Integer(), nullable=False),
    sa.Column('hashed_code', sa.String(length=200), nullable=False),
    sa.Column('generated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('length_of_stay', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['LU_role.role_id'], ),
    sa.PrimaryKeyConstraint('trust_code_id'),
    sa.UniqueConstraint('hashed_code')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('surName', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('account_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['LU_role.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conservation_entry',
    sa.Column('conservation_entry_id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=False),
    sa.Column('gbif_taxonomy_id', sa.String(length=100), nullable=True),
    sa.Column('conservation_list_id', sa.Integer(), nullable=False),
    sa.Column('conservation_status_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conservation_list_id'], ['LU_conservation_list.conservation_list_id'], ),
    sa.ForeignKeyConstraint(['conservation_status_id'], ['LU_conservation_status.conservation_status_id'], ),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.taxonomy_id'], ),
    sa.PrimaryKeyConstraint('conservation_entry_id')
    )
    with op.batch_alter_table('conservation_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conservation_entry_gbif_taxonomy_id'), ['gbif_taxonomy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conservation_entry_scientific_name'), ['scientific_name'], unique=False)

    op.create_table('report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('public_latitude', sa.Float(), nullable=True),
    sa.Column('public_longitude', sa.Float(), nullable=True),
    sa.Column('numbers_of_sighted', sa.Integer(), nullable=True),
    sa.Column('habitat_sighted', sa.String(length=200), nullable=True),
    sa.Column('report_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('image_id', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_status_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_status_id'], ['LU_report_status.report_status_id'], ),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.taxonomy_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('taxonomy_conservation_status',
    sa.Column('taxonomy_id', sa.Integer(), nullable=False),
    sa.Column('conservation_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conservation_status_id'], ['LU_conservation_status.conservation_status_id'], ),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.taxonomy_id'], ),
    sa.PrimaryKeyConstraint('taxonomy_id', 'conservation_status_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxonomy_conservation_status')
    op.drop_table('report')
    with op.batch_alter_table('conservation_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conservation_entry_scientific_name'))
        batch_op.drop_index(batch_op.f('ix_conservation_entry_gbif_taxonomy_id'))

    op.drop_table('conservation_entry')
    op.drop_table('user')
    op.drop_table('trust_codes')
    with op.batch_alter_table('taxonomy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxonomy_is_protected'))
        batch_op.drop_index(batch_op.f('ix_taxonomy_gbif_taxonomy_id'))

    op.drop_table('taxonomy')
    op.drop_table('LU_conservation_status')
    op.drop_table('LU_taxonomy_rank')
    op.drop_table('LU_role')
    op.drop_table('LU_report_status')
    op.drop_table('LU_data_source')
    op.drop_table('LU_conservation_list')
    op.drop_table('LU_authority')
    # ### end Alembic commands ###
